### ISSUE TITLE
Cannot find libvips with multiple buildpacks

### ISSUE THREAD

**Issue by h2non** [alex88/heroku-buildpack-vips#15]
I'm using this buildpack in conjunction with other one, via [buildpack-multi](https://github.com/ddollar/heroku-buildpack-multi).

For some reason, when the next buildpack is compiled, `PKG_CONFIG_PATH` is not available, therefore failing the compilation. Seems like the buildpacks environment variables are not properly propagated between buildpacks.

If a create a unique buildpack with all the compilation code of both required buildpacks, it works!

Do you have a similar experience running multiple buildpacks?

**Comment by psirenny** [comment]
I have the same issue.

**Comment by alex88** [comment]
@h2non sorry for the delay, I'm a bit busy at work. Anyway, can you create a sample repo that generates that error?

I think something changed because many guys were using this buildpack for node.js applications and it was working fine.

**Comment by h2non** [comment]
Sure! If you try to use this buildpack with golang, for instance, the buildpack. The problem is the propagation of the PKG_CONFIG_PATH env var. For some reason, the variables declared in `.profile.d` are not properly loaded by the next buildpack (golang). 

To solve this I created my own buildpack, based on the golang original buildpack. 
Basically it merge both buildpack `compile` scripts:
https://github.com/h2non/heroku-buildpack-imaginary/blob/master/bin/compile#L4

**Comment by pusewicz** [comment]
I'm using it with ruby buildpack too and that's what I get:

```
remote:        Could not detect rake tasks
remote:        ensure you can run `$ bundle exec rake -P` against your app with no environment variables present
remote:        and using the production group of your Gemfile.
remote:        rake aborted!
remote:        LoadError: libvips.so.40: cannot open shared object file: No such file or directory - /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/ruby-vips-0.3.9/vips_ext.so
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/ruby-vips-0.3.9/lib/vips.rb:4:in `<top (required)>'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/vips-process-0.2.3/lib/vips-process.rb:1:in `<top (required)>'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `each'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `block in require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `each'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler.rb:134:in `require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/config/application.rb:16:in `<top (required)>'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/Rakefile:4:in `require'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/Rakefile:4:in `<top (required)>'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
remote:        /tmp/build_936722e4ab36b80d809ba4901fd8b393/vendor/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
remote:        vendor/bundle/bin/rake:16:in `load'
remote:        vendor/bundle/bin/rake:16:in `<main>'
```

**Comment by alex88** [comment]
@pusewicz have you recently upgraded the buildpack version? Since in that case you need to rebuild the vips ruby extension (e.g. by changing ruby version in Gemfile)

**Comment by flosky** [comment]
Hi Alex,

I'm also having trouble with the buildpack on heroku. I have a node app and want to use the sharp module. I set your buildpack as the default one but I get this error

    remote: Building source:
    remote: 
    remote: -----> Fetching custom git buildpack... done
    remote: 
    remote:  !     Push rejected, no Cedar-supported app detected
    remote: HINT: This occurs when Heroku cannot detect the buildpack
    remote:       to use for this application automatically.
    remote: See https://devcenter.heroku.com/articles/buildpacks

Then I also added the default node buildpack with

    heroku buildpacks:add <node buildpack url>

But this only uses the default node buildpack as fallback and therefore fails when calling npm install, since there is no libvips installed on that one.

**Comment by alex88** [comment]
@flosky aren't you using https://github.com/ddollar/heroku-buildpack-multi?

**Comment by flosky** [comment]
No

**Comment by alex88** [comment]
@flosky you've to use that, I've updated the readme telling it must be used

**Comment by pusewicz** [comment]
@alex88 Bumping the version of Ruby did not work. Still having the same problem.
